// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  res.status(200).json({
    results: [
      {
        id: 1,
        name: "Tony Reichert",
        semester: "Fall",
        country: "USA",
        status: "active",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        email: "tony.reichert@example.com",
      },
      {
        id: 2,
        name: "Zoey Lang",
        semester: "Fall",
        country: "USA",
        status: "paused",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
        email: "zoey.lang@example.com",
      },
      {
        id: 3,
        name: "Jane Fisher",
        semester: "Spring",
        country: "USA",
        status: "active",
        avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
        email: "jane.fisher@example.com",
      },
      {
        id: 4,
        name: "William Howard",
        semester: "Spring",
        country: "USA",
        status: "vacation",
        avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
        email: "william.howard@example.com",
      },
      {
        id: 5,
        name: "Kristen Copper",
        semester: "Fall",
        country: "USA",
        status: "active",
        avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
        email: "kristen.cooper@example.com",
      },
      {
        id: 6,
        name: "Brian Kim",
        semester: "Spring",
        country: "USA",
        status: "active",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        email: "brian.kim@example.com",
      },
      {
        id: 7,
        name: "Michael Hunt",
        semester: "Fall",
        country: "USA",
        status: "paused",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
        email: "michael.hunt@example.com",
      },
      {
        id: 8,
        name: "Samantha Brooks",
        semester: "Fall",
        country: "USA",
        status: "active",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
        email: "samantha.brooks@example.com",
      },
      {
        id: 9,
        name: "Frank Harrison",
        semester: "Fall",
        country: "USA",
        status: "vacation",
        avatar: "https://i.pravatar.cc/150?img=4",
        email: "frank.harrison@example.com",
      },
      {
        id: 10,
        name: "Emma Adams",
        semester: "Fall",
        country: "USA",
        status: "active",
        avatar: "https://i.pravatar.cc/150?img=5",
        email: "emma.adams@example.com",
      },
      {
        id: 11,
        name: "Brandon Stevens",
        semester: "Spring",
        country: "USA",
        status: "active",
        avatar: "https://i.pravatar.cc/150?img=8",
        email: "brandon.stevens@example.com",
      },
      {
        id: 12,
        name: "Megan Richards",
        semester: "Spring",
        country: "USA",
        status: "paused",
        avatar: "https://i.pravatar.cc/150?img=10",
        email: "megan.richards@example.com",
      },
      {
        id: 13,
        name: "Oliver Scott",
        semester: "Spring",
        country: "USA",
        status: "active",
        avatar: "https://i.pravatar.cc/150?img=12",
        email: "oliver.scott@example.com",
      },
      {
        id: 14,
        name: "Grace Allen",
        semester: "Fall",
        country: "USA",
        status: "active",
        avatar: "https://i.pravatar.cc/150?img=16",
        email: "grace.allen@example.com",
      },
      {
        id: 15,
        name: "Noah Carter",
        semester: "Fall",
        country: "USA",
        status: "paused",
        avatar: "https://i.pravatar.cc/150?img=15",
        email: "noah.carter@example.com",
      },
      {
        id: 16,
        name: "Ava Perez",
        semester: "Fall",
        country: "USA",
        status: "active",
        avatar: "https://i.pravatar.cc/150?img=20",
        email: "ava.perez@example.com",
      },
      {
        id: 17,
        name: "Liam Johnson",
        semester: "Fall",
        country: "USA",
        status: "active",
        avatar: "https://i.pravatar.cc/150?img=33",
        email: "liam.johnson@example.com",
      },
      {
        id: 18,
        name: "Sophia Taylor",
        semester: "Fall",
        country: "USA",
        status: "active",
        avatar: "https://i.pravatar.cc/150?img=29",
        email: "sophia.taylor@example.com",
      },
      {
        id: 19,
        name: "Lucas Harris",
        semester: "Fall",
        country: "USA",
        status: "paused",
        avatar: "https://i.pravatar.cc/150?img=50",
        email: "lucas.harris@example.com",
      },
      {
        id: 20,
        name: "Mia Robinson",
        semester: "Fall",
        country: "USA",
        status: "active",
        avatar: "https://i.pravatar.cc/150?img=45",
        email: "mia.robinson@example.com",
      },
    ],
  });
}
